### ISSUE TITLE
Number of repositories is limited to 100

### ISSUE THREAD

**Issue by mfornasa** [infinityworks/github-exporter#20]
I am trying to scrape an organisation with more than 100 repos. I am getting only first 100.

**Comment by flock3** [comment]
Hey @mfornasa 

Super open to pull requests to implement pagination support in the Github Exporter. Alternatively, you could provide the container with a list of repositories as an array (via REPOS environment variable) and that will allow you to return data for >100 repos.

**Comment by mfornasa** [comment]
@flock3 thank you for the workaround.

**Comment by dgrizzanti** [comment]
@mfornasa have you had any issues when running with more than a handle of repos? If I give an ORG that has 100 repos, trying to access `/metrics` just hangs forever

**Comment by alexellis** [comment]
I also have this issue.. :-1:
