### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by linlynn** [infinityworks/github-exporter#23]
docker version 17.06.0-ce

lynn@lynn-ThinkCentre-M92p:~/github-exporter$ sudo docker build -t github-exporter:1.0 .
Sending build context to Docker daemon  114.7kB
Step 1/13 : FROM golang:1.8.0-alpine as build
 ---> bcb935bbf1da
Step 2/13 : LABEL maintainer "Infinity Works"
 ---> Using cache
 ---> 3a629a30802d
Step 3/13 : RUN apk --update add ca-certificates      && apk --update add --virtual build-deps git
 ---> Running in d054829967c2
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.c51f8f92.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.d09172fd.tar.gz: No such file or directory
OK: 5 MiB in 12 packages
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/main: temporary error (try again later)
WARNING: Ignoring APKINDEX.c51f8f92.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.5/community: temporary error (try again later)
WARNING: Ignoring APKINDEX.d09172fd.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  build-deps-0:
    masked in: cache
    satisfies: world[build-deps]
  git (missing):
    required by:
The command '/bin/sh -c apk --update add ca-certificates      && apk --update add --virtual build-deps git' returned a non-zero code: 2

**Comment by Rucknar** [comment]
Just pulled master and run the same command, worked okay. From the error i'm inclined to think this was an issue with an alpine package distribution repository. Could you please give it another try?

**Comment by linlynn** [comment]
@Rucknar  not sure if it is related with my corporate network . I will try it with my home network

**Comment by linlynn** [comment]
works now
