### ISSUE TITLE
Can you please vendor dependencies or use go modules

### ISSUE THREAD

**Issue by williamh** [infinityworks/github-exporter#33]
Hi, I am working on packaging this project for Gentoo.

it looks like it imports many external packages. However, they are not vendored and go modules [1] are not used.

Would you please consider vendoring your dependencies or using Go modules [1]?

This would make building this exporter much easier for packagers and allow reproducible builds.

Thanks much.

[1] https://github.com/golang/go/wiki/Modules

**Comment by Rucknar** [comment]
Agreed sounds sensible.

**Comment by alexellis** [comment]
I've done a soft fork here to perform some of the updates I've seen requested by the community including this issue. https://github.com/alexellis/github-exporter
