### ISSUE TITLE
Making a docker hub release with a precise version.

### ISSUE THREAD

**Issue by remyleone** [infinityworks/github-exporter#47]
Could you make a release on Docker hub: https://hub.docker.com/r/infinityworks/github-exporter/tags using the latest only cannot guarantee that we will have a pinned version of this software. Semver could be a nice versioning schema: https://semver.org/

In the meantime, we will use SHA256 of the docker image as a pinned version.

**Comment by ANDKRI** [comment]
@remyleone - I really like your idea and would also be happy about this change. 
@all - Is there a realistic chance?

**Comment by ogruene** [comment]
Hi,

I would also highly appreciate creating a versioned release on Dockerhub. I completely agree with @remyleone that using `latest` tag is not a good idea for the same reason.

Thank you.

Oliver Grüneberg <oliver.grueneberg@daimler.com>, Daimler TSS GmbH

[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)

**Comment by joemonaghan-iw** [comment]
This has now been implemented. You can get the current version using the `release-1.0.0` tag.
