### ISSUE TITLE
Set LISTEN_PORT in the Prometheus assigned port (9171) by default 

### ISSUE THREAD

**Issue by gsanchezgavier** [infinityworks/github-exporter#55]
Hi currently the default port for the `LISTEN_PORT` variable is 8080 and should be [9171](https://github.com/prometheus/prometheus/wiki/Default-port-allocations)

When running the exporter outside the container `LISTEN_PORT` needs to be set and that could be avoided. Setting this property to 9171 by default would be the expected behavior since that is the port reserved for this exporter.

**Comment by Rucknar** [comment]
@gsanchezgavier I might be missing something here but for myself it's pulling this through already through the go-common library. 
```
		logLevel:    GetEnv("LOG_LEVEL", "debug"),

```

**Comment by gsanchezgavier** [comment]
@Rucknar  go-common sets the the `LISTEN_PORT` to 8080 by default. I would expect that by default this exporter binds the port 9171 (reserved by prometheus for this particular exporter).
I'm not sure what would be the implications to modify the go-common library so i did the change in the config section of the exporter.

**Comment by Rucknar** [comment]
I think it's because i consume the docker image where it's set in the Dockerfile, you're right it does seem to be 8080. Truth be told the go-common stuff isn't really necessary anymore. Let me have a proper look.
